---
title: "Temporal variation in reporting delays"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{temporal_variation_in_reporting}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(incidenceinflation)
library(ggplot2)
library(magrittr)
library(dplyr)
library(tidyr)
library(purrr)
```

In a real epidemic, the reporting delays may vary over time. In this vignette, we illustrate how this package can be used to simulate then fit a model allowing for temporally varying delays in case reporting.

```{r}
days_total <- 100

# allow Rt to vary over time and construct interpolation function
v_Rt <- c(rep(1.5, 40), rep(0.4, 20), rep(1.5, 40))
Rt_function <- stats::approxfun(1:days_total, v_Rt)

# serial interval distribution parameters (assumed gamma)
s_params <- list(mean=5, sd=3)

# negative binomial over-dispersion parameter
kappa <- 10

# specify a reporting distribution that shortens after the first 50 days
r_params <- tibble(
  time_onset=seq(1, days_total, 1),
  mean=c(rep(10, 50), rep(3, 50)),
  sd=c(rep(3, 50), rep(2, 50))
)

# generate data
df <- generate_snapshots(days_total, Rt_function, s_params, r_params,
                         kappa=kappa)
```

At t=40, there is large discrepancies between the cases reported and the true cases.
```{r}
t <- 40
df %>% 
  filter(time_onset <= t) %>% 
  filter(time_reported >= t) %>% 
  ggplot(aes(x=time_onset, y=cases_reported)) +
  geom_line(aes(colour=time_reported,
                group=time_reported)) +
  geom_point(aes(y=cases_true), colour="black") +
  geom_line(aes(y=cases_true), colour="black") +
  scale_colour_viridis_c(begin = 0.2)
```

At t=90, these are much less marked.
```{r}
t <- 90
df %>% 
  filter(time_onset <= t) %>% 
  filter(time_reported >= t) %>% 
  ggplot(aes(x=time_onset, y=cases_reported)) +
  geom_line(aes(colour=time_reported,
                group=time_reported)) +
  geom_point(aes(y=cases_true), colour="black") +
  geom_line(aes(y=cases_true), colour="black") +
  scale_colour_viridis_c(begin = 0.2)
```

